### ISSUE TITLE
Getting `FileNotFound` error when calling `run_hst1pass`

### ISSUE THREAD

**Issue by masolimano** [spacetelescope/wfc3_photometry#5]
Hello there!
I am trying to run the example notebook,  but I'm having issues with the fitting procedures. The data retrieval went smoothly, but then the Fortran interface fitting fails immediately with the following message
```python
Using PSF file PSFSTD_WFC3UV_F814W.fits
~/arcos/notebooks/wfc3_photometry/psf_tools/hst1pass_linux.e HMIN=5 FMIN=1000 PMAX=66000 OUT=xympqks GDC=NONE PSF=PSFSTD_WFC3UV_F814W.fits ictj45ahq_flc.fits ictj45ahq_flc.fits ictj45ajq_flc.fits ictj45b9q_flc.fits ictj46csq_flc.fits ictj46cuq_flc.fits ictj46czq_flc.fits
ictj45ahq_flc.xympqks

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-34-3998a40c8fd3> in <module>
----> 1 catalogs = psf.run_hst1pass(input_images, hmin=5, fmin=1000, pmax=66000)

~/arcos/notebooks/wfc3_photometry/psf_tools/PSFPhot.py in run_hst1pass(input_images, hmin, fmin, pmax, out, executable_path, **kwargs)
    615     print(cmd)
    616     run_and_print_output(cmd)
--> 617     make_chip_catalogs(expected_output_list)
    618     return expected_output_list
    619 

~/arcos/notebooks/wfc3_photometry/psf_tools/CatalogUtils.py in make_chip_catalogs(input_catalogs)
    115         image_name = image_root + '.fits'
    116 
--> 117         tmp = read_one_pass_tbl(cat_name)
    118         chip = tmp['k'].data.astype(int)
    119         inds = chip == 1 # the chip 1 indices

~/arcos/notebooks/wfc3_photometry/psf_tools/CatalogUtils.py in read_one_pass_tbl(input_catalog)
    210     """
    211 
--> 212     penultimate_line = open(input_catalog).readlines()[-2]
    213     cols = penultimate_line.strip('#').replace('.', '').split()
    214     derp = np.loadtxt(input_catalog)

FileNotFoundError: [Errno 2] No such file or directory: 'ictj45ahq_flc.xympqks'
```
I believe the script is wanting that the catalogs were already built.
Could it be the version of the packages I'm using are too new?
My environment uses:
- `python==3.8.2`
- `photutils==0.7.2`
- `skimage==0.16.2`
- `astropy==4.0`
- `drizzlepac==3.1.6`
- `astroquery==0.3.10`

The Python interface does run, but then fails:

```python
Using PSF file PSFSTD_WFC3UV_F814W.fits
ictj45ahq_flc.fits
Rejected 2749 of 6579 sources for being too peaked
Rejected 2358 more sources after qmax and excess clip
ictj45ajq_flc.fits
Rejected 13650 of 28438 sources for being too peaked

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/manuel/arcos/notebooks/wfc3_photometry/psf_tools/PyFitting.py", line 314, in fit_star
    f, x, y = popt
ValueError: too many values to unpack (expected 3)
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-48-f1dfb0210b67> in <module>
----> 1 catalogs = psf.run_python_psf_fitting(['ictj45ahq_flc.fits',
      2 'ictj45ajq_flc.fits'])

~/arcos/notebooks/wfc3_photometry/psf_tools/PyFitting.py in run_python_psf_fitting(input_images, psf_model_file, hmin, fmin, pmax, qmax, cmin, cmax, ncpu)
     86         for ext in exts:
     87             data = fits.getdata(im , extname='SCI', extver=ext)
---> 88             tbl = measure_stars(data, mods[ext-1], hmin, fmin, pmax,
     89                                 qmax, cmin, cmax, ncpu)
     90             tbl['x'] += 1.

~/arcos/notebooks/wfc3_photometry/psf_tools/PyFitting.py in measure_stars(data, mod, hmin, fmin, pmax, qmax, cmin, cmax, ncpu)
    160     # Measure the remaining candidates
    161 
--> 162     tbl = do_stars_mp(xs, ys, skies, mod, data, ncpu)
    163     # Last rejection pass
    164     final_good_mask = (tbl['q']<qmax) & (tbl['cx']<cmax) & (tbl['cx']>cmin)

~/arcos/notebooks/wfc3_photometry/psf_tools/PyFitting.py in do_stars_mp(xs, ys, skies, mod, data, ncpu)
    346         p = Pool(ncpu)
    347 
--> 348     result = p.starmap(fit_func, xy_sky)
    349     p.close()
    350     p.join()

/usr/lib/python3.8/multiprocessing/pool.py in starmap(self, func, iterable, chunksize)
    370         `func` and (a, b) becomes func(a, b).
    371         '''
--> 372         return self._map_async(func, iterable, starmapstar, chunksize).get()
    373 
    374     def starmap_async(self, func, iterable, chunksize=None, callback=None,

/usr/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    766             return self._value
    767         else:
--> 768             raise self._value
    769 
    770     def _set(self, i, obj):

ValueError: too many values to unpack (expected 3)
```
When I have time I will create an astroconda environment with the exact same versions of the packages you listed. If it works I will close this issue :).

Best,
Manuel

**Comment by Vb2341** [comment]
I'm not sure of what the issue with the python interface is quite yet (could be that I mixed up my branches between development/stable versions and forgot to remove some bits), but I think I might understand what the issue is with the fortran version.  Generally the no such file or directory error is due to the fortran  program crashing, and thus not generating any catalogs, causing the python code to process those catalogs to crash.  I don't yet have a good way of catching when the fortran code fails, but it does typically output the status messages of the fortran code in the terminal that you initiated the notebook in, and there might be details there.

Also, it looks like in the command thats executed, the first image is listed twice.  I'm not sure how that would break anything, but perhaps that has something to do with it.  Could you post the commands you used to run the code?

Apologies for the bugs- this feedback should help sort them out though!

**Comment by masolimano** [comment]
Hi @Vb2341, thanks for the quick reply!
>  it does typically output the status messages of the fortran code in the terminal that you initiated the notebook in, and there might be details there.

You were right, I checked the console and found
```
~/arcos/notebooks/wfc3_photometry/psf_tools/hst1pass_linux.e: error while loading shared libraries: libgfortran.so.3: cannot open shared object file: No such file or directory
```
I don't have that soname link installed, and does not belong to the current gcc runtime packages available for my distro, so I guess the fix would be to re-build the binary using my version of the libraries. But I'm not able to do so because I don't have any of the external libraries invoked at the end of the `hst1pass.F` file. Other option I should check is try to run the binary in an older OS (I'm running Arch btw, but I have access to a centos7 box).

>Also, it looks like in the command thats executed, the first image is listed twice.

:O didn't see that. I removed the duplicate from the list but didn't work :c

For the record, what I ran was:
```python
from wfc3_photometry.psf_tools import run_hst1pass, run_python_psf_fitting
# Hard coded the name of the files to make sure there are no duplicates
# These are the longest-exposure F814W images of the Omega Cen dataset
input_images = ['ictj45ajq_flc.fits', 
      'ictj45b9q_flc.fits',
      'ictj46cuq_flc.fits',
      'ictj46czq_flc.fits']

hmin = 5
fmin = 1000.
pmax= 66000.
catalogs = run_hst1pass(input_images=input_images, hmin=hmin, fmin=fmin, pmax=pmax)
# this fails with the FileNotFoundError (after binary crashing bc libgfortran.so.3 file is missing)
catalogs = run_python_psf_fitting(input_images,  hmin=hmin, fmin=fmin, pmax=pmax) 
# this fails  with ValueError (see above)
```

**Comment by Vb2341** [comment]
So I've looked at the code a bit more, and I think I figured out the issues with the python engine.  Unfortunately, I am far from being an expert with the Fortran side, so I'm really not sure how to go about fixing the library error, as distributing all the source files would I think require a large overhaul to how they are written.

That said, I think my latest commits should fix the python engine issues, though I haven't fully vetted that yet.  You can try pulling those changes and then rerunning the code, and hopefully that will fix the ValueError.

**Comment by masolimano** [comment]
Great! I ran the example notebook on my CentOS box and the Fortran binary works as expected, so I may indeed be a distro compatibility problem. The Python interface also seems to be fixed, since it executed correctly without the ValueError :smiley:. 

Though I haven't tested with other data, I think this solves the issue :+1: .
